version: '3'

services: 
  application:
    build:
      context: ./app
    container_name: application
    image: arthurdonizetti/desafio-docker-nginx-app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s npm start
    networks: 
      - nginx-network
    volumes:
      - ./app/src:/usr/src/app/src
    tty: true
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
    container_name: db
    image: arthurdonizetti/desafio-docker-nginx-database
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=nginxdb
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=root
    networks:
     - nginx-network

  nginx:
    build:
      context: ./nginx
    image: arthurdonizetti/desafio-docker-nginx
    # entrypoint: dockerize -wait tcp://application:3000 -timeout 40s
    container_name: nginx
    networks:
      - nginx-network
    ports:
      - "8080:80"
    depends_on: 
      - application

networks:
  nginx-network:
    driver: bridge
